### ISSUE TITLE
unused parameters when --noUnusedParameters is on

### ISSUE THREAD

**Issue by mrkvon** [blacksonic/ngx-http-test#7]
Hello, when i use `ngx-http-test` with `"noUnusedParameters": true` in my `tsconfig.json`, i get the following errors:

```
ERROR in [path-to-project]/node_modules/ngx-http-test/src/backend-expectation.ts (54,35): 'values' is declared but never used.

ERROR in [path-to-project]/node_modules/ngx-http-test/src/fake-backend.ts (124,32): 'connection' is declared but never used.
```

If the above parameters `connection` and `values` were renamed to `_connection` and `_values`, the error would disappear. Would such a fix be possible?

It is an `angular-cli` project if that makes any difference.

**Comment by sonicoder86** [comment]
Should be fixed with version 1.3.2
